### PR TITLE
GitHub workflows

### PR DESCRIPTION
**Pull request by JuniorIsAJitterbug**
These are manually triggered builds.

Tested decoding and `ld-analyse` on Linux/Windows/macOS x86_64 builds, macOS arm64 build untested.

Initial Windows tools build will take about an hour but should be cached afterwards.

macOS releases are `.dmg` that install to `/Applications/{vhs_decode,tbc-tools}.app`. Users can add the `Content/MacOS` directories to `$PATH` if they want. The arm64 build does not contain FlaLDF.

Unsure if AppImages will be compatible with all distros, only tested on NixOS and Ubuntu 22.04.

Icons by @harrypm.

### CODE REVIEW

**Comment by JuniorIsAJitterbug** [comment]
PyPI workflow requires [trusted publishing](https://docs.pypi.org/trusted-publishers/creating-a-project-through-oidc/) to be setup.

An environment needs to be created on GitHub named `pypi`. The workflow name is `push_pypi.yml`.

**Comment by oyvindln** [comment]
Is there some way to test the pypi workflow locally and e.g with test-pypi? also do source wheel need to be built for multiple python versions?

**Comment by JuniorIsAJitterbug** [comment]
Do you want a test-pypi workflow? It's just adding changing the url and the environment name.

I don't think the sdist needs to be built for each version so it's created once, only the wheels are built for multiple python versions.

**Comment by oyvindln** [comment]
As in there a way to test locally without having to run it on github a million times. last time I looked into pypi I had to mess around with the pyproject files a bunch of times as it was very strict about how projects were structured

**Pull request merged**
