### PR TITLE
fix typos in Readme.md

### PR DESCRIPTION
**Pull request by Randrianasulu**

### CODE REVIEW

**Comment by harrypm** [comment]
@Randrianasulu ''Not supported in big NLEs'' well it's not supported by many smaller ones very well either, nor is it supported by authoring software for DVD/Blu-Ray mastering (Not that there is much past Sony DVD Architect these days) also EVS and other broadcast system support is out too.

It is supported by a handful of NLEs but there is a reason behind pushing DaVinci Resolve as a defacto its base is free for SD-1080p production but it's incredibly easy to grade and set levels properly and its the growing industry standard for mastering.

**Comment by Randrianasulu** [comment]
@harrypm thing is, I prefer GNU/Linux ( Slackware, especially) for reason - even barely-developer like me can fix minor bugs, sometimes! Also meta-monopoly of proprietary "solutions" sooner or latter will runt into contradiction between extracting a bit more money and user's needs. Guess what most likely to win by default :-)

Still, I try not to be hostile to win/mac users - if you have win machine with cygwin or wsl2 I encorage you to try our cinelerra-gg and report bugs :) Same for mac machine.

For porting cx raw driver to win - look into reactos here on github - there are some people working on win-compatible drivers, so may be they can help with this.

**Comment by qwertychouskie** [comment]
> @harrypm thing is, I prefer GNU/Linux

FWIW, DaVinci Resolve will run on Linux systems.

**Comment by Randrianasulu** [comment]
> > @harrypm thing is, I prefer GNU/Linux
> 
> FWIW, DaVinci Resolve will run on Linux systems.

Yet, it remain proprietary, and currently require OpenCL/OpenGL interoperability not present in mesa drivers. May be think about ability to look/fix/share as "right to repair", but for software ..

**Pull request merged**
